Add a debug panel with memory measurements.
vaadin/dashboard-demo pull request #38
Opened 2018-08-28 11:08 UTC by SomeoneToIgnore

The panel is opened with Ctrl + Login ( Cmd + Login for mac also) button click.

2018-08-28 11:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/dashboard-demo?pullRequest=38) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/dashboard-demo?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/dashboard-demo?pullRequest=38) it.</sub>

2018-08-28 13:01 UTC, gilberto-torrezan requested changes

2018-08-28 13:01 UTC, gilberto-torrezan commented on src/main/java/com/vaadin/demo/dashboard/view/MainView.java
> +                System.out.println("GC happened: " + gcEvent.toString());
Is this read somewhere?

2018-08-28 13:01 UTC, gilberto-torrezan commented on src/main/java/com/vaadin/demo/dashboard/view/MainView.java
> +                    totalMemoryMB += measurement.value() / 1024 / 1024;
When you divide by 1024 * 1024, you don't have MB (megabyte), but MiB (mebibyte). To have MB you should divide by the standard 1000 * 1000.

Courtesy of the HDD manufacturers.

2018-08-28 13:10 UTC, SomeoneToIgnore commented on src/main/java/com/vaadin/demo/dashboard/view/MainView.java
> +                    totalMemoryMB += measurement.value() / 1024 / 1024;
Oh, ok, thanks.

2018-08-28 13:10 UTC, SomeoneToIgnore commented on src/main/java/com/vaadin/demo/dashboard/view/MainView.java
> +                System.out.println("GC happened: " + gcEvent.toString());
Yes, in the console.
Not needed by the tests but interesting to see how many garbage and where has been removed.

2018-08-28 13:36 UTC, gilberto-torrezan approved these changes

2018-08-28 13:38 UTC, merged

2018-08-29 12:51 UTC, Legioth commented
A much less obtrusive way would have been to deploy an additional servlet that returns a text with the current memory usage.

2018-08-29 12:52 UTC, SomeoneToIgnore commented
We can improve it later, sure.

2018-08-29 12:52 UTC, SomeoneToIgnore commented
Not sure about the MPR servlet – are multiple servlets supported there also?

2018-08-29 12:53 UTC, SomeoneToIgnore commented
Also, current method is easy enough to use manually by just opening the website.

Not sure about obtrusiveness also – the panel is not shown for simple login.